### ISSUE TITLE
[Setting] MVVM 구조 셋팅, Hilt 도입

### ISSUE THREAD

**Issue by plashdof** [inha-commit/egusajo-android#3]
## TODO 
- [x] MVVM 구조 셋팅
- [x] Hilt Module 추가
- [x] Splash Activity 추가
